-- Evolution gene run persistence table (MVP).
-- Use this script when you want to create table manually in PostgreSQL.

CREATE TABLE IF NOT EXISTS public.evolution_gene_runs (
    -- Unique id for one evolution run across scoring and commit events.
    run_id TEXT PRIMARY KEY,
    -- Iteration number from orchestrator loop.
    iteration INTEGER NOT NULL DEFAULT 0,
    -- Run status from StrategyScored event: ok/rejected/unknown.
    status TEXT NOT NULL DEFAULT 'unknown',
    -- Composite score generated by MemoryAgent.
    score DOUBLE PRECISION NULL,
    -- Strategy identity extracted from generated strategy code.
    strategy_id TEXT NOT NULL DEFAULT '',
    strategy_name TEXT NOT NULL DEFAULT '',
    -- Parent strategy lineage.
    parent_strategy_id TEXT NOT NULL DEFAULT '',
    parent_strategy_name TEXT NOT NULL DEFAULT '',
    -- Gene lineage snapshot.
    child_gene_id TEXT NOT NULL DEFAULT '',
    child_gene_parent_ids JSONB NOT NULL DEFAULT '[]'::jsonb,
    child_gene_fingerprint TEXT NOT NULL DEFAULT '',
    child_gene_family TEXT NOT NULL DEFAULT '',
    -- Serialized metrics/profile payloads from events.
    metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
    profile JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Hash only to avoid storing large strategy source repeatedly.
    strategy_code_sha256 TEXT NOT NULL DEFAULT '',
    -- Commit linkage after StrategyCommitted event.
    committed_strategy_id TEXT NOT NULL DEFAULT '',
    committed_strategy_name TEXT NOT NULL DEFAULT '',
    committed_version INTEGER NOT NULL DEFAULT 0,
    committed_at TIMESTAMPTZ NULL,
    -- Audit timestamps.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_egr_iteration ON public.evolution_gene_runs (iteration);
CREATE INDEX IF NOT EXISTS idx_egr_created_at ON public.evolution_gene_runs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_egr_child_gene_id ON public.evolution_gene_runs (child_gene_id);
CREATE INDEX IF NOT EXISTS idx_egr_child_gene_fp ON public.evolution_gene_runs (child_gene_fingerprint);
CREATE INDEX IF NOT EXISTS idx_egr_child_gene_family ON public.evolution_gene_runs (child_gene_family);
